name: jax_v_torch
channels:
- defaults
- conda-forge
dependencies:
- python=3.10.4
- pip=22.1.2
- pip:
  - dm-haiku==0.0.6
  - flax==0.5.1
  - optax==0.1.2
  - chex==0.1.3
  - mnist==0.2.2
  - torch==1.11
  - micro-config==0.1.2
  - tqdm==4.64.0
  - wandb==0.12.18
  - dm-tree==0.1.7
  - "jax[cpu]"
